insert into produto (id, descricao, preco) values (1, 'notebook i7 8gb', 4500);
insert into produto (id, descricao, preco) values (2, 'monitor 21', 800);
insert into produto (id, descricao, preco) values (3, 'smart tv 50', 2000);
insert into produto (id, descricao, preco) values (4, 'smartphone snapdragon 898', 1800);
insert into produto (id, descricao, preco) values (5, 'cadeira escritorio', 500);
insert into produto (id, descricao, preco) values (6, 'caixa bluetooth', 200);
insert into produto (id, descricao, preco) values (7, 'joystick wireless', 100);
insert into produto (id, descricao, preco) values (8, 'roteador 4 portas', 200);
insert into produto (id, descricao, preco) values (9, 'impressora multi wireless', 1500);
insert into produto (id, descricao, preco) values (10, 'teclado abnt pt-br usb', 30);
insert into produto (id, descricao, preco) values (11, 'teclado abnt pt-br wireless', 100);
insert into produto (id, descricao, preco) values (12, 'mouse usb', 10);
insert into produto (id, descricao, preco) values (13, 'mouse wireless', 50);